### ISSUE TITLE
No Output when Running BAMs with GRCh38.d1.vd1 Reference

### ISSUE THREAD

**Issue by marcobuttigieg** [weinstockj/pileup_region#1]
```
module load StdEnv/2020 rust/1.65.0
cargo build --release

./target/release/pileup_region U2AF1_region_file.txt <bam> GRCh38.d1.vd1.fa
```
[U2AF1_region_file.txt](https://github.com/weinstockj/pileup_region/files/11618032/U2AF1_region_file.txt)
[GRCh38.d1.vd1.fa.tar.gz](https://api.gdc.cancer.gov/data/254f697d-310d-4d7d-a27b-27fbf767a834)

When I tried running the pileup_region script as shown above on our compute cluster there is no output generated. Any help is greatly appreciated!

**Comment by weinstockj** [comment]
Hi Marco - could you please try again with the latest version of the code on the master branch? I pushed an update today that may address this.

**Comment by marcobuttigieg** [comment]
Hi Josh - it works great now! Thanks so much!!

**Comment by weinstockj** [comment]
Great! Thanks for letting me know.
